### ISSUE TITLE
twitter无法访问。youtube视频不能观看

### ISSUE THREAD

**Issue by zhaozhongchen** [liuker0x007/hosts#5]
你好。感谢你提供hosts文件。但是在我的电脑上，twitter打不开。youtube虽然能够打开，但是其视频不能观看。能不能解决一下？谢谢。

**Comment by liuker0x007** [comment]
非常感谢你的反馈。
1、前几天已经更新了，以及修复了Twitter、Google、facebook等hosts。
2、这个hosts是不能观看YouTube的视频。关于解决的方法：你可以通过这个网站把视频下载下来http://www.onlinevideoconverter.com/video-converter。
3、这个hosts主要是Google、Twitter等hosts，方便我们在学习的过程中，更好的查找资料。还有就是Twitter有一些大牛，加他们的Twitter可以更好的学习。

**Comment by liuker0x007** [comment]
非常感谢你的反馈。
1、前几天已经更新了，以及修复了Twitter、Google、facebook等hosts。
2、这个hosts是不能观看YouTube的视频。关于解决的方法：你可以通过这个网站把视频下载下来http://www.onlinevideoconverter.com/video-converter。
3、这个hosts主要是Google、Twitter等hosts，方便我们在学习的过程中，更好的查找资料。还有就是Twitter有一些大牛，加他们的Twitter可以更好的学习。

**Comment by zhaozhongchen** [comment]
你好，感谢帮助，问题已经解决。
非常感谢！

**Comment by kgfw** [comment]
这里有个 [hosts翻墙](https://github.com/bannedbook/fanqiang/wiki/hosts%E7%BF%BB%E5%A2%99)  ，可以看youtube,还可以看很多海外禁网新闻，速度不错
