### ISSUE TITLE
README.md 里的命令不正确

### ISSUE THREAD

**Issue by zepinglee** [liuker0x007/hosts#6]
> **1.Use terminal:**  

> Use wget or curl，eg:   
> Open Terminal(Hot key: "Ctrl + Alt + T"), input `bash -c 'wget https://github.com/liuker0x007/hosts/blob/master/hosts -qO /tmp/hosts && sudo mv /tmp/hosts /etc/hosts'`.

这个地址是html，应该使用 https://raw.githubusercontent.com/liuker0x007/hosts/master/hosts

**Comment by liuker0x007** [comment]
thank you~
